parameters:
  appName:  '$(WebAppNameDev)'

steps:
- task: AzureWebApp@1
  displayName: 'Azure App Service Deploy: website'
  inputs:
    azureSubscription: 'Resource Manager - Mk- Space Game'
    appName: '$({parameters.appName]})'
    package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'